import './globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import Header from '@/components/layout/Header';
import NuqsProvider from '@/components/providers/NuqsProvider';
import TanstackProvider from '@/components/providers/TanstackProvider';
import { Provider as JotaiProvider } from 'jotai';

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'PocketDex V2',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-bg-base min-h-screen flex flex-col items-center text-text gap-5 antialiased`}
      >
        <TanstackProvider>
          <NuqsProvider>
            <JotaiProvider>
              <Header />
              {children}
            </JotaiProvider>
          </NuqsProvider>
        </TanstackProvider>
      </body>
    </html>
  );
}
